version: 0.0
os: windows
files:
  - source: /
    destination: C:\temp
hooks:
  BeforeInstall:
    - location: deploy/scripts/BeforeInstall.ps1
      timeout: 900
  AfterInstall:
    - location: deploy/scripts/AfterInstall.ps1
      timeout: 900
  ApplicationStart:
    - location: deploy/scripts/ApplicationStart.ps1
